// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMytable = "mytables"

// Mytable mapped from table <mytables>
type Mytable struct {
	ID       int64   `gorm:"column:ID;not null" json:"-"`
	Username *string `gorm:"column:username;index:idx_username,priority:1" json:"-"`
	Age      int64   `gorm:"column:age;not null" json:"-"`
	Phone    string  `gorm:"column:phone;not null" json:"-"`
}

// TableName Mytable's table name
func (*Mytable) TableName() string {
	return TableNameMytable
}
